config/routes.rb
Rails.application.routes.draw do
  resources :forum_threads, only: [:index, :show, :create, :new]
  resources :conversations, only: [:create, :new]

  root 'forum_threads#index'

end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id               :integer          not null, primary key
#  subject          :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  parent_thread_id :integer
#
# Indexes
#
#  index_forum_threads_on_parent_thread_id  (parent_thread_id)
#

class ForumThread < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :subject
  after_validation :sanitize_words

  has_many :child_threads, :class_name => "ForumThread", :foreign_key => "parent_thread_id"
  belongs_to :parent_thread, :class_name => "ForumThread"

  scope :orphan, -> { where(parent_thread: nil) }

  private
  def sanitize_words
    words = self.subject.split(" ")
    words.each_with_index do |word,index|
      if bad_word?(word)
        words[index] = replace word  
      end
    end
    self.subject = words.join(" ")
  end

  def replace(word)
    '*' * word.size
  end

  def bad_word?(word) 
    Rails.application.config.blacklist.include?(word)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :load_parent
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def new
    @forum_thread = ForumThread.find params[:parent_id]
    @child_thread  = ForumThread.new(parent_thread_id: params[:parent_id])
  end

  def create
    @parent_thread = ForumThread.find params[:parent_thread_id]
    @parent_thread.child_threads.build forum_thread_params

    if @parent_thread.save
      redirect_to forum_thread_path(@parent_thread)
    else
      @forum_thread = @parent_thread 
      render 'forum_threads/show'
    end
  end

  private

  def forum_thread_params
    params.permit :parent_thread_id, :subject
  end

end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController

  def index
    @forum_threads = ForumThread.orphan().paginate(:page => params[:page])
    @child_thread  = ForumThread.new
  end

  def show
    @forum_thread = ForumThread.includes(:child_threads).find(params[:id])
    @child_threads= @forum_thread.child_threads.paginate(:page => params[:page], :per_page => 5)
    @child_thread = ForumThread.new parent_thread: @forum_thread
  end

  def new
    @parent_thread  = ForumThread.new(parent_thread_id: params[:parent_id])
  end

  def create
    @parent_thread = ForumThread.new(forum_thread_params)

    if @parent_thread.save
      redirect_to forum_threads_path
    else
      render :new
    end
  end

  private

  def forum_thread_params
    params.require(:forum_thread).permit :parent_thread_id, :subject
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def fast_link(text, link, html_options='')
    %(<a href="#{request.base_url}/#{link}">#{text}</a>).html_safe
  end

  def thread_link(text, link)
    fast_link(text, "forum_threads/#{link}", 'class="forum_thread_link"')
  end
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/conversations/_form_reply.html.erb
<%= form_tag(conversations_path, :method=>'post') do %>
  <%= hidden_field_tag :parent_thread_id, "#{@forum_thread.id}" %>
  <ul>
    <% @child_thread.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= label_tag "Adicionar Resposta".to_sym if @child_thread.parent_thread %><br />
    <%= text_field_tag :subject %>
  </p>
  
  <p>
    <%= submit_tag %>
  </p>
<% end %>

app/views/conversations/new.html.erb
<%= render "form_reply" %>

app/views/forum_threads/_child_thread.html.erb
<li class="child_thread">
  <h3><%= child_thread.subject %> | 
   
  <span><%= link_to 'Responder', new_conversation_path(parent_id: child_thread) %> </span>
  </h3>
   
  <% unless child_thread.child_threads.empty? %>
    <ul class="child_thread_list">
      <%= render :partial => 'child_thread', :collection => child_thread.child_threads %>
    </ul>
  <% end %>
</li>

app/views/forum_threads/_form.html.erb
<%= form_for @parent_thread = ForumThread.new do |f| %>
  <ul>
    <% @parent_thread.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :Assunto %><br />
    <%= f.text_field :subject %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/forum_threads/index.html.erb
<h1 id="page_title">Main Thread Board</h1>

<%= render 'form' %>

<table>
  <tr>
    <th align="left">Assunto</th>
  </tr>
 
<% @forum_threads.each do |thread| %>
  <tr>
    <td><%= thread_link "#{thread.subject}", "#{thread.id}" %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @forum_threads %>

app/views/forum_threads/new.html.erb
<%= render "form" %>

app/views/forum_threads/show.html.erb
<h1><%= "Lista de respostas da conversa #{@forum_thread.subject}" %></h1>

<ul class="child_threads_list">
  <%= render :partial => 'forum_threads/child_thread', :collection => @forum_thread.child_threads %>
</ul>

<%= render 'conversations/form_reply' %>

<%= will_paginate @child_threads %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marvintalks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <div id="wrapper">
        <div id="top_nav">
            <h1>
              <%= link_to root_path do %>
                <%= image_tag("logo.jpg", :size => '50x50') %>
                <span> Marvin Talks forum to the galaxy </span>
              <%end%>
            </h1>
            
            <%# if current_user %>
            <%# link_to "Edit Profile", edit_user_registration_url(current_user.id)%> 
            <%# link_to "Logout", :logout %>
            <%# else %>
            <%# link_to "Register", new_user_registration_path %>  
            <%# link_to "Login", destroy_user_session_path %>
            <%# end %>
            <div class="bclear"></div>
        </div>
        
    
        <div id="content">
            <%= yield %>
        </div>
 
        <div id="footer">
 
        </div>
    </div>
</body>
</html>